<?php
/**
 * Created by PhpStorm.
 * User: zhouhua
 * Date: 2015-10-19
 * Time: 16:18
 */

namespace task;


use datatype\StarDataObj;
use datatype\StarPicGroup;
use datatype\StarPicture;

class Task_YunWeekPicDown extends TaskBase
{
    public $taskurl;

    public function startTask()
    {
        parent::startTask(); // TODO: Change the autogenerated stub




        $doc=$this->featchDoc($this->taskurl);

        $urlinfo=parse_url($this->taskurl);

        print_r($urlinfo);

//        return;
//        echo pq($doc)->html();

        $images=pq($doc)->find("img");

//        print_r($images);
        foreach($images as $image){
            $title=$urlinfo["scheme"]."://".$urlinfo["host"]."/";
            $url=$title.pq($image)->attr("src");
            $picinfo=parse_url($url);

            $filename=$picinfo["path"];
            $fileay=explode("/",$filename);
            $filename=array_pop($fileay);

            print_r($picinfo);
            echo "filename=".$filename."\n";
//            continue;
            if(strpos($url,".jpg")>0){

                echo "[image]".$url."\n";

                $filedir="./downweek/";

                $this->getImage($url,$filedir,$filename);
            }



        }



//        $this->getResult();

//        $this->ProccDocName($doc);






    }

    private $taskpics;

    public function getResult()
    {

        return $this->taskpics; // TODO: Change the autogenerated stub
    }


    public function ProccDocName(\phpQueryObject $doc){


        $div=pq(".img_box");

            $this->taskpics=[];



            $pic=new StarPicture();

            $pic->picindex=0;

            $pic->picurl=pq($div)->find("a")->find("img")->attr("src");

            echo $pic->intro().PHP_EOL;


            $this->taskpics[]=$pic;

            $filedir="./down/".$this->taskobj->starname."/".$this->taskobj->groupname;

            $filedir=str_replace("\n","",$filedir);

            $filename=$this->taskobj->starname.".jpg";
            echo "[Down]".$pic->picurl." =>". $filedir."/".$filename.PHP_EOL;
             $this->getImage($pic->picurl,$filedir,$filename);



        }




}