<?php
/**
 * Created by PhpStorm.
 * User: zhouhua
 * Date: 2015-10-19
 * Time: 16:18
 */

namespace task;


use datatype\StarDataObj;

class Task_StartName extends TaskBase
{
    public $taskurl;

    public function startTask()
    {
        parent::startTask(); // TODO: Change the autogenerated stub


        $doc=$this->featchDoc($this->taskurl);


        $this->ProccDocName($doc);

//        if($this->taskStars){
//
//            $this->onTaskComp(true);
//        }
//        else{
//            $this->onTaskComp(false);
//        }

        return $this->getResult();

    }

    private $taskStars;

    public function getResult()
    {
        return $this->taskStars; // TODO: Change the autogenerated stub
    }


    public function ProccDocName(\phpQueryObject $doc){


        $div=pq(".ulbox");

        $liList=$div->find("li");

        $this->taskStars=[];


        foreach($liList as $li){

            $star=new StarDataObj();

            $star->name=pq($li)->find("h3")->text();
            $star->homepage=pq($li)->find("h3")->find("a")->attr("href");


            $taskdir="./down/".$star->name;

            if(!file_exists($taskdir)){
                mkdir($taskdir);
            }
            else{
                echo "己存在的项目: ".$star->name.PHP_EOL;
                continue;
            }

            $this->taskStars[]=$star;



            echo $star->intro()."\n";

//            return;
        }

    }

}