<?php
/**
 * Created by PhpStorm.
 * User: zhouhua
 * Date: 2015-10-19
 * Time: 16:18
 */

namespace task;


use datatype\JBHPic;
use datatype\StarDataObj;
use datatype\StarPicGroup;
use datatype\StarPicture;

class Task_JBHDown extends TaskBase
{
    public $taskurl;


    public function startTask()
    {
        parent::startTask(); // TODO: Change the autogenerated stub


        $this->taskurl= $this->taskobj->homepage;

//        $this->taskurl="http://www.jianbihua.cc/dongwu/68263.html";

        echo "[Load TaskUrl]:".$this->taskurl.PHP_EOL;


        $pageinfo=explode("/",$this->taskurl);
        array_pop($pageinfo);

        $thispagedir=join("/",$pageinfo);






        $doc=$this->featchDoc($this->taskurl);

        $this->childpageurls=$this->getAllChildpages($doc,$thispagedir);

        $countpage=count($this->childpageurls);



        for($i=0;$i<$countpage;$i++){

            $childpage=$this->childpageurls[$i];

            echo "[INFO]Load Child Page:".$childpage.PHP_EOL;

            $childdoc=$this->featchDoc($childpage);

            $this->ProccDocName($childdoc,$i);

        }




//






    }

    private $childpageurls;

    private $taskpics;

    public function getResult()
    {

        return $this->taskpics; // TODO: Change the autogenerated stub
    }


    public function getAllChildpages(\phpQueryObject $doc,$thispagedir){


        $div=pq(".listpage");

        $lilist=$div->find("li");

        $pages=[];

        $pages[]=$this->taskurl;

        foreach($lilist as $li){

            $linkhref=pq($li)->find("a")->attr("href");



            if($linkhref==""){
                continue;
            }
            else if($linkhref=="#"){

                $linkhref=$this->taskurl;
            }
            else{
                $linkhref=$thispagedir."/".$linkhref;
            }



            if(array_search($linkhref,$pages)===false){

                $pages[]=$linkhref;
                echo "[INFO]add child page:".$linkhref.PHP_EOL;
            }



        }

        return $pages;
    }


    public function ProccDocName(\phpQueryObject $doc,$docindex){

//        return;
        $div=pq(".mybody");

            $this->taskpics=[];



            $pic=new JBHPic();

            $pic->picindex=0;

            $imglist=pq($div)->find("img");

            $count=0;

            foreach($imglist as $img){


                $pic->picindex=$count;
                $pic->picurl=pq($img)->attr("src");
                $count++;

                $filenameinfo=explode("/",$pic->picurl);
                $filename=$filenameinfo[count($filenameinfo)-1];


                echo PHP_EOL."Pic".$count."=".$pic->intro().PHP_EOL;


                $this->taskpics[]=$pic;

                $filedir=$this->taskobj->downdir;



                echo "[Down]".$pic->picurl." =>". $filedir."/".$filename.PHP_EOL;

                $this->getImage($pic->picurl,$filedir,$filename);


            }








        }



    /*
    *
    *功能：php完美实现下载远程图片保存到本地
    *参数：文件url,保存文件目录,保存文件名称，使用的下载方式
    *当保存文件名称为空时则使用远程文件原来的名称
    */
    function getImage($url,$save_dir='',$filename='',$type=0){
        if(trim($url)==''){
            return array('file_name'=>'','save_path'=>'','error'=>1);
        }
        if(trim($save_dir)==''){
            $save_dir='./';
        }
        if(trim($filename)==''){//保存文件名
            $ext=strrchr($url,'.');
            // if($ext!='.gif'&&$ext!='.jpg'){
            //   return array('file_name'=>'','save_path'=>'','error'=>3);
            //  }
            $filename=time().$ext;
        }
        if(0!==strrpos($save_dir,'/')){
            $save_dir.='/';
        }
        //创建保存目录
        if(!file_exists($save_dir)&&!mkdir($save_dir)){
            return array('file_name'=>'','save_path'=>'','error'=>5);
        }
        //获取远程文件所采用的方法
        if($type){
            $ch=curl_init();
            $timeout=5;
            curl_setopt($ch,CURLOPT_URL,$url);
            curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
            curl_setopt($ch,CURLOPT_CONNECTTIMEOUT,$timeout);
            $img=curl_exec($ch);
            curl_close($ch);
        }else{
            ob_start();
            readfile($url);
            $img=ob_get_contents();
            ob_end_clean();
        }
        //$size=strlen($img);
        //文件大小
        $fp2=@fopen($save_dir.$filename,'a');
        fwrite($fp2,$img);
        fclose($fp2);
        unset($img,$url);
        return array('file_name'=>$filename,'save_path'=>$save_dir.$filename,'error'=>0);
    }


}